/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CourseType = IDL.Variant({
  'practical' : IDL.Null,
  'theory' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'semester' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'isActive' : IDL.Bool,
  'courseType' : CourseType,
});
export const LeaveType = IDL.Variant({
  'permission' : IDL.Null,
  'leave' : IDL.Null,
  'onDuty' : IDL.Null,
});
export const LeaveEntry = IDL.Record({
  'id' : IDL.Nat,
  'isApproved' : IDL.Bool,
  'studentId' : IDL.Nat,
  'date' : IDL.Text,
  'approvedBy' : IDL.Text,
  'leaveType' : LeaveType,
  'courseId' : IDL.Text,
});
export const Student = IDL.Record({
  'id' : IDL.Nat,
  'semester' : IDL.Nat,
  'parentContact' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'section' : IDL.Text,
  'isActive' : IDL.Bool,
  'batch' : IDL.Nat,
  'rollNo' : IDL.Text,
});
export const Teacher = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AttendanceStatus = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : AttendanceStatus,
  'studentId' : IDL.Nat,
  'period' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'sectionOrBatch' : IDL.Text,
  'teacherId' : IDL.Nat,
  'courseId' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalStudents' : IDL.Nat,
  'todayAttendanceCount' : IDL.Nat,
  'totalTeachers' : IDL.Nat,
  'totalCourses' : IDL.Nat,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Nat,
  'date' : IDL.Text,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const StudentFilters = IDL.Record({
  'semester' : IDL.Opt(IDL.Nat),
  'year' : IDL.Opt(IDL.Nat),
  'section' : IDL.Opt(IDL.Text),
  'batch' : IDL.Opt(IDL.Nat),
});
export const AttendanceInput = IDL.Record({
  'studentId' : IDL.Nat,
  'isPresent' : IDL.Bool,
});
export const AttendanceSubmission = IDL.Record({
  'records' : IDL.Vec(AttendanceInput),
  'period' : IDL.Nat,
  'date' : IDL.Text,
  'sectionOrBatch' : IDL.Text,
  'teacherId' : IDL.Nat,
  'courseId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(UserProfile)], []),
  'createTeacherAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'addCourse' : IDL.Func([Course], [IDL.Nat], []),
  'addLeaveEntry' : IDL.Func([LeaveEntry], [IDL.Nat], []),
  'addStudent' : IDL.Func([Student], [IDL.Nat], []),
  'addTeacher' : IDL.Func([Teacher], [IDL.Nat], []),
  'approveLeave' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllLeaveEntries' : IDL.Func([], [IDL.Vec(LeaveEntry)], ['query']),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
  'getAttendanceByCourse' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByStudent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getNotifications' : IDL.Func([IDL.Nat], [IDL.Vec(Notification)], ['query']),
  'getStudentsByFilter' : IDL.Func(
      [StudentFilters],
      [IDL.Vec(Student)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitAttendance' : IDL.Func([AttendanceSubmission], [], []),
  'updateCourse' : IDL.Func([IDL.Nat, Course], [], []),
  'updateStudent' : IDL.Func([IDL.Nat, Student], [], []),
  'updateTeacher' : IDL.Func([IDL.Nat, Teacher], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CourseType = IDL.Variant({
    'practical' : IDL.Null,
    'theory' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'semester' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'isActive' : IDL.Bool,
    'courseType' : CourseType,
  });
  const LeaveType = IDL.Variant({
    'permission' : IDL.Null,
    'leave' : IDL.Null,
    'onDuty' : IDL.Null,
  });
  const LeaveEntry = IDL.Record({
    'id' : IDL.Nat,
    'isApproved' : IDL.Bool,
    'studentId' : IDL.Nat,
    'date' : IDL.Text,
    'approvedBy' : IDL.Text,
    'leaveType' : LeaveType,
    'courseId' : IDL.Text,
  });
  const Student = IDL.Record({
    'id' : IDL.Nat,
    'semester' : IDL.Nat,
    'parentContact' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'section' : IDL.Text,
    'isActive' : IDL.Bool,
    'batch' : IDL.Nat,
    'rollNo' : IDL.Text,
  });
  const Teacher = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AttendanceStatus = IDL.Variant({
    'present' : IDL.Null,
    'absent' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : AttendanceStatus,
    'studentId' : IDL.Nat,
    'period' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'sectionOrBatch' : IDL.Text,
    'teacherId' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalStudents' : IDL.Nat,
    'todayAttendanceCount' : IDL.Nat,
    'totalTeachers' : IDL.Nat,
    'totalCourses' : IDL.Nat,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Nat,
    'date' : IDL.Text,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const StudentFilters = IDL.Record({
    'semester' : IDL.Opt(IDL.Nat),
    'year' : IDL.Opt(IDL.Nat),
    'section' : IDL.Opt(IDL.Text),
    'batch' : IDL.Opt(IDL.Nat),
  });
  const AttendanceInput = IDL.Record({
    'studentId' : IDL.Nat,
    'isPresent' : IDL.Bool,
  });
  const AttendanceSubmission = IDL.Record({
    'records' : IDL.Vec(AttendanceInput),
    'period' : IDL.Nat,
    'date' : IDL.Text,
    'sectionOrBatch' : IDL.Text,
    'teacherId' : IDL.Nat,
    'courseId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(UserProfile)], []),
    'createTeacherAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'changePassword' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'addCourse' : IDL.Func([Course], [IDL.Nat], []),
    'addLeaveEntry' : IDL.Func([LeaveEntry], [IDL.Nat], []),
    'addStudent' : IDL.Func([Student], [IDL.Nat], []),
    'addTeacher' : IDL.Func([Teacher], [IDL.Nat], []),
    'approveLeave' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllLeaveEntries' : IDL.Func([], [IDL.Vec(LeaveEntry)], ['query']),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getAllStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'getAllTeachers' : IDL.Func([], [IDL.Vec(Teacher)], ['query']),
    'getAttendanceByCourse' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByStudent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getStudentsByFilter' : IDL.Func(
        [StudentFilters],
        [IDL.Vec(Student)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitAttendance' : IDL.Func([AttendanceSubmission], [], []),
    'updateCourse' : IDL.Func([IDL.Nat, Course], [], []),
    'updateStudent' : IDL.Func([IDL.Nat, Student], [], []),
    'updateTeacher' : IDL.Func([IDL.Nat, Teacher], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
