/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceInput { 'studentId' : bigint, 'isPresent' : boolean }
export interface AttendanceRecord {
  'id' : bigint,
  'status' : AttendanceStatus,
  'studentId' : bigint,
  'period' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'sectionOrBatch' : string,
  'teacherId' : bigint,
  'courseId' : bigint,
}
export type AttendanceStatus = { 'present' : null } |
  { 'absent' : null };
export interface AttendanceSubmission {
  'records' : Array<AttendanceInput>,
  'period' : bigint,
  'date' : string,
  'sectionOrBatch' : string,
  'teacherId' : bigint,
  'courseId' : bigint,
}
export interface Course {
  'id' : bigint,
  'semester' : bigint,
  'code' : string,
  'name' : string,
  'year' : bigint,
  'isActive' : boolean,
  'courseType' : CourseType,
}
export type CourseType = { 'practical' : null } |
  { 'theory' : null };
export interface DashboardStats {
  'totalStudents' : bigint,
  'todayAttendanceCount' : bigint,
  'totalTeachers' : bigint,
  'totalCourses' : bigint,
}
export interface LeaveEntry {
  'id' : bigint,
  'isApproved' : boolean,
  'studentId' : bigint,
  'date' : string,
  'approvedBy' : string,
  'leaveType' : LeaveType,
  'courseId' : string,
}
export type LeaveType = { 'permission' : null } |
  { 'leave' : null } |
  { 'onDuty' : null };
export interface Notification {
  'id' : bigint,
  'studentId' : bigint,
  'date' : string,
  'isRead' : boolean,
  'message' : string,
}
export interface Student {
  'id' : bigint,
  'semester' : bigint,
  'parentContact' : string,
  'name' : string,
  'year' : bigint,
  'section' : string,
  'isActive' : boolean,
  'batch' : bigint,
  'rollNo' : string,
}
export interface StudentFilters {
  'semester' : [] | [bigint],
  'year' : [] | [bigint],
  'section' : [] | [string],
  'batch' : [] | [bigint],
}
export interface Teacher {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'email' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'login' : ActorMethod<[string, string], [] | [UserProfile]>,
  'createTeacherAccount' : ActorMethod<[string, string, string], boolean>,
  'changePassword' : ActorMethod<[string, string, string], boolean>,
  'addCourse' : ActorMethod<[Course], bigint>,
  'addLeaveEntry' : ActorMethod<[LeaveEntry], bigint>,
  'addStudent' : ActorMethod<[Student], bigint>,
  'addTeacher' : ActorMethod<[Teacher], bigint>,
  'approveLeave' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllLeaveEntries' : ActorMethod<[], Array<LeaveEntry>>,
  'getAllNotifications' : ActorMethod<[], Array<Notification>>,
  'getAllStudents' : ActorMethod<[], Array<Student>>,
  'getAllTeachers' : ActorMethod<[], Array<Teacher>>,
  'getAttendanceByCourse' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getAttendanceByDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceByStudent' : ActorMethod<[bigint], Array<AttendanceRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getNotifications' : ActorMethod<[bigint], Array<Notification>>,
  'getStudentsByFilter' : ActorMethod<[StudentFilters], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitAttendance' : ActorMethod<[AttendanceSubmission], undefined>,
  'updateCourse' : ActorMethod<[bigint, Course], undefined>,
  'updateStudent' : ActorMethod<[bigint, Student], undefined>,
  'updateTeacher' : ActorMethod<[bigint, Teacher], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
